# Generated by Django 2.0.2 on 2018-11-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0002_victima_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victima',
            options={'ordering': ['order', 'title'], 'verbose_name': 'objetivo', 'verbose_name_plural': 'objetivos'},
        ),
    ]
